keys:
   - &user_dshore age1vw58rr3ayl4qmqm76rgh4kffktmpteyqmfs6q6unr4mrnxuzvg4qf0ke84
   - &host_office age1syjllnswmkex3ngscc98e569d2al5j76c32m2sahlrmeff03k5hs4d4jgk
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_dshore
          - *host_office
